name: CI
on:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: pnpm/action-setup@v6
        with:
          cache: true
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm tsc
      - run: pnpm build
      - run: pnpm test
      - run: pnpm check-dts
